services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db_demo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_demo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb #il nome del server, deve matchare con quello in riga 2
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - mongo_network

volumes:
  mongo: {}

networks:
  mongo_network:
    driver: bridge